name = "task-app"
main = "server/index.ts"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]

assets = { directory = "./dist/client", binding = "ASSETS" }

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
invocation_logs = true

[[d1_databases]]
binding = "DB"
database_name = "task-app-local"
database_id = "00000000-0000-0000-0000-000000000000"
migrations_dir = "./server/db/migrations"

[triggers]
crons = ["0 3 * * *"]

[env.production]
name = "task-app"

[[env.production.d1_databases]]
binding = "DB"
database_name = "task-app-prod"
database_id = "3605a196-43db-4276-adc9-61ef66dca5ab"
migrations_dir = "./server/db/migrations"

[env.develop]
name = "task-app-develop"

[[env.develop.d1_databases]]
binding = "DB"
database_name = "task-app-develop"
database_id = "78d203ca-d97d-43a7-9ba1-0cc7572cff50"
migrations_dir = "./server/db/migrations"
