name: Actions CI

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/**'
      - '.github/actions/**'

concurrency:
  group: actions-ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
      - uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8  # v2.1.2
        with:
          version: 1.7.7
